services:
  postgres:
    image: postgres:17-alpine
    container_name: restaurant-pos-db
    environment:
      POSTGRES_DB: restaurant_pos
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
