INSERT INTO menu_items (id, name_en, name_km, description_en, description_km, price, currency_id, image_url, available, category_id, created_at, updated_at) VALUES 
(gen_random_uuid(), 'Christmas Set Meal', 'Christmas Set Meal', 'DIY Base + USA Beef + Crab Stick + Broccoli + Needle Mushroom + Milky Spicy Soup + Pineapple Lemon Jasmine Tea', 'DIY Base + USA Beef + Crab Stick + Broccoli + Needle Mushroom + Milky Spicy Soup + Pineapple Lemon Jasmine Tea', 2.80, '24a528e9-7a85-423b-9c0f-39f72e815b14', '/uploads/promo/xmas_promo.jpg', true, '2603ea50-b86e-4ab7-afd0-23a27855abd7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Lunar New Year Set', 'Lunar New Year Set', 'DIY Base + Tender Chicken + Fish Roe Meatball + Lotus Roots + Handmade Noodles + Chicken Broth Soup + Red Apple Jasmine Tea', 'DIY Base + Tender Chicken + Fish Roe Meatball + Lotus Roots + Handmade Noodles + Chicken Broth Soup + Red Apple Jasmine Tea', 3.35, '24a528e9-7a85-423b-9c0f-39f72e815b14', '/uploads/promo/lunar_promo.jpg', true, '2603ea50-b86e-4ab7-afd0-23a27855abd7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(gen_random_uuid(), 'Halloween Spooky Set', 'Halloween Spooky Set', 'DIY Base + Black Chicken + Duck Blood + Black Fungus + Potato Noodles + Sichuan Spicy Soup + Honey Lemon Kiss', 'DIY Base + Black Chicken + Duck Blood + Black Fungus + Potato Noodles + Sichuan Spicy Soup + Honey Lemon Kiss', 2.65, '24a528e9-7a85-423b-9c0f-39f72e815b14', '/uploads/promo/halloween_promo.jpg', true, '2603ea50-b86e-4ab7-afd0-23a27855abd7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO guest_promo (title, description, image_url, is_active, created_at, updated_at) VALUES 
('Merry Christmas Promo!', 'Enjoy our Christmas Set Meal for only $2.80 (25% Off!). Includes USA Beef, Crab Stick, Broccoli, Needle Mushroom, Milky Spicy Soup, and Pineapple Lemon Tea.', '/uploads/promo/xmas_promo.jpg', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lunar New Year Special', 'Celebrate with our Lunar New Year Set for only $3.35 (20% Off!). Includes Tender Chicken, Fish Roe Meatball, Lotus Roots, Handmade Noodles, Chicken Broth, and Red Apple Tea.', '/uploads/promo/lunar_promo.jpg', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Spooky Halloween Set', 'Try our Halloween Set for only $2.65 (30% Off!). Includes Black Chicken, Duck Blood, Black Fungus, Potato Noodles, Sichuan Spicy Soup, and Honey Lemon Kiss.', '/uploads/promo/halloween_promo.jpg', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
