/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["resetPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_1"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/{id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["markReady"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/{id}/lines/{lineId}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["voidLine"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["cancel"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modifier-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_2"];
        put: operations["update_2"];
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_3"];
        put: operations["update_3"];
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/cart/lines/{lineId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateLine"];
        post?: never;
        delete: operations["removeLine"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_4"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_4"];
        put: operations["update_5"];
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/{id}/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/{id}/qr-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["regenerateQrToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSessionRounds"];
        put?: never;
        post: operations["submitRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/modifier-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu-items/{menuItemId}/modifier-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getForMenuItem"];
        put?: never;
        post: operations["attach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu-items/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/cart/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/cart/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addLine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_4"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBySession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}/bill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/receipts/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/menu/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/menu/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getItemDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/menu/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCart"];
        put?: never;
        post?: never;
        delete: operations["clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAll_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu-items/{menuItemId}/modifier-groups/{modifierGroupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["detach"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserUpdateRequest: {
            /** Format: email */
            email: string;
            enabled: boolean;
            roles: ("ADMIN" | "CASHIER")[];
        };
        ApiResponseUserResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            username?: string;
            email?: string;
            enabled?: boolean;
            roles?: ("ADMIN" | "CASHIER")[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PasswordResetRequest: {
            newPassword: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
            /** Format: date-time */
            timestamp?: string;
        };
        TableUpdateRequest: {
            tableNumber: string;
            active: boolean;
        };
        ApiResponseTableResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TableResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        TableResponse: {
            /** Format: uuid */
            id?: string;
            tableNumber?: string;
            qrToken?: string;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseCashierRoundResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CashierRoundResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        CashierRoundResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sessionId?: string;
            tableNumber?: string;
            /** Format: int32 */
            roundNumber?: number;
            /** @enum {string} */
            status?: "SENT" | "READY" | "COMPLETED" | "CANCELLED";
            subtotal?: number;
            vatRate?: number;
            vatAmount?: number;
            grandTotal?: number;
            /** Format: date-time */
            sentAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
            cancelReason?: string;
            lines?: components["schemas"]["OrderRoundLineResponse"][];
        };
        OrderRoundLineResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            menuItemId?: string;
            nameEn?: string;
            nameKm?: string;
            basePrice?: number;
            unitPrice?: number;
            /** Format: int32 */
            quantity?: number;
            lineTotal?: number;
            remark?: string;
            voided?: boolean;
            voidReason?: string;
            selections?: components["schemas"]["OrderRoundSelectionResponse"][];
        };
        OrderRoundSelectionResponse: {
            /** Format: uuid */
            modifierOptionId?: string;
            nameEn?: string;
            nameKm?: string;
            unitPrice?: number;
            /** Format: int32 */
            quantity?: number;
        };
        ReasonRequest: {
            reason: string;
        };
        ModifierGroupUpdateRequest: {
            nameEn: string;
            nameKm: string;
            /** Format: int32 */
            minChoice: number;
            /** Format: int32 */
            maxChoice?: number;
            active?: boolean;
            options: components["schemas"]["ModifierOptionRequest"][];
        };
        ModifierOptionRequest: {
            /** Format: uuid */
            id?: string;
            nameEn: string;
            nameKm: string;
            imageUrl?: string;
            unitPrice: number;
            packSize?: string;
            available?: boolean;
            /** Format: int32 */
            sortOrder: number;
        };
        ApiResponseModifierGroupResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ModifierGroupResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ModifierGroupResponse: {
            /** Format: uuid */
            id?: string;
            nameEn?: string;
            nameKm?: string;
            /** Format: int32 */
            minChoice?: number;
            /** Format: int32 */
            maxChoice?: number;
            active?: boolean;
            options?: components["schemas"]["ModifierOptionResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ModifierOptionResponse: {
            /** Format: uuid */
            id?: string;
            nameEn?: string;
            nameKm?: string;
            imageUrl?: string;
            unitPrice?: number;
            packSize?: string;
            available?: boolean;
            /** Format: int32 */
            sortOrder?: number;
        };
        MenuItemUpdateRequest: {
            nameEn: string;
            nameKm: string;
            descriptionEn?: string;
            descriptionKm?: string;
            price: number;
            currencyCode: string;
            available?: boolean;
            /** Format: uuid */
            categoryId: string;
        };
        ApiResponseMenuItemResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MenuItemResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        MenuItemResponse: {
            /** Format: uuid */
            id?: string;
            nameEn?: string;
            nameKm?: string;
            descriptionEn?: string;
            descriptionKm?: string;
            price?: number;
            currencyCode?: string;
            imageUrl?: string;
            available?: boolean;
            /** Format: uuid */
            categoryId?: string;
            categoryNameEn?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CartLineUpdateRequest: {
            /** Format: int32 */
            quantity: number;
            remark?: string;
            selections?: components["schemas"]["CartSelectionRequest"][];
        };
        CartSelectionRequest: {
            /** Format: uuid */
            modifierOptionId: string;
            /** Format: int32 */
            quantity: number;
        };
        ApiResponseCartResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CartResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        CartLineResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            menuItemId?: string;
            nameEn?: string;
            nameKm?: string;
            imageUrl?: string;
            basePrice?: number;
            /** Format: int32 */
            quantity?: number;
            remark?: string;
            selections?: components["schemas"]["CartSelectionResponse"][];
            unitPrice?: number;
            lineTotal?: number;
        };
        CartResponse: {
            /** Format: uuid */
            sessionId?: string;
            lines?: components["schemas"]["CartLineResponse"][];
            currencyCode?: string;
            subtotal?: number;
            vatRate?: number;
            vatAmount?: number;
            grandTotal?: number;
            grandTotalKhr?: number;
        };
        CartSelectionResponse: {
            /** Format: uuid */
            modifierOptionId?: string;
            nameEn?: string;
            nameKm?: string;
            unitPrice?: number;
            /** Format: int32 */
            quantity?: number;
        };
        ExchangeRateUpdateRequest: {
            rate: number;
            /** Format: date */
            effectiveDate: string;
        };
        ApiResponseExchangeRateResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExchangeRateResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ExchangeRateResponse: {
            /** Format: uuid */
            id?: string;
            fromCurrencyCode?: string;
            toCurrencyCode?: string;
            rate?: number;
            /** Format: date */
            effectiveDate?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CategoryUpdateRequest: {
            nameEn: string;
            nameKm: string;
            description?: string;
            /** Format: int32 */
            sortOrder: number;
            active?: boolean;
        };
        ApiResponseCategoryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CategoryResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        CategoryResponse: {
            /** Format: uuid */
            id?: string;
            nameEn?: string;
            nameKm?: string;
            description?: string;
            /** Format: int32 */
            sortOrder?: number;
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        TableCreateRequest: {
            tableNumber: string;
        };
        ApiResponseStaffSessionResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["StaffSessionResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        StaffSessionResponse: {
            /** Format: uuid */
            sessionId?: string;
            /** Format: uuid */
            tableId?: string;
            tableNumber?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED";
            /** Format: date-time */
            createdAt?: string;
        };
        CartLineAddRequest: {
            /** Format: uuid */
            menuItemId: string;
            /** Format: int32 */
            quantity: number;
            remark?: string;
            selections?: components["schemas"]["CartSelectionRequest"][];
        };
        CashierRoundRequest: {
            lines: components["schemas"]["CartLineAddRequest"][];
        };
        PaymentRequest: {
            /** @enum {string} */
            method: "CASH" | "QR";
            amountTendered?: number;
            currency?: string;
            referenceNote?: string;
        };
        ApiResponseReceiptResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReceiptResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        BillResponse: {
            /** Format: uuid */
            sessionId?: string;
            tableNumber?: string;
            /** @enum {string} */
            sessionStatus?: "ACTIVE" | "CLOSED";
            rounds?: components["schemas"]["OrderRoundResponse"][];
            currencyCode?: string;
            subtotal?: number;
            vatAmount?: number;
            grandTotal?: number;
            grandTotalKhr?: number;
        };
        OrderRoundResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            roundNumber?: number;
            /** @enum {string} */
            status?: "SENT" | "READY" | "COMPLETED" | "CANCELLED";
            subtotal?: number;
            vatRate?: number;
            vatAmount?: number;
            grandTotal?: number;
            /** Format: date-time */
            sentAt?: string;
            lines?: components["schemas"]["OrderRoundLineResponse"][];
        };
        PaymentResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            method?: "CASH" | "QR";
            billTotal?: number;
            amountTendered?: number;
            tenderedCurrency?: string;
            changeUsd?: number;
            changeKhr?: number;
            referenceNote?: string;
            paidBy?: string;
            /** Format: date-time */
            paidAt?: string;
        };
        ReceiptResponse: {
            restaurantName?: string;
            /** Format: uuid */
            receiptId?: string;
            receiptNumber?: string;
            /** Format: date-time */
            openedAt?: string;
            /** Format: date-time */
            closedAt?: string;
            bill?: components["schemas"]["BillResponse"];
            payment?: components["schemas"]["PaymentResponse"];
        };
        ModifierGroupCreateRequest: {
            nameEn: string;
            nameKm: string;
            /** Format: int32 */
            minChoice: number;
            /** Format: int32 */
            maxChoice?: number;
            active?: boolean;
            options: components["schemas"]["ModifierOptionRequest"][];
        };
        MenuItemCreateRequest: {
            nameEn: string;
            nameKm: string;
            descriptionEn?: string;
            descriptionKm?: string;
            price: number;
            currencyCode: string;
            available?: boolean;
            /** Format: uuid */
            categoryId: string;
        };
        AttachModifierGroupRequest: {
            /** Format: uuid */
            modifierGroupId: string;
            /** Format: int32 */
            sortOrder: number;
        };
        ApiResponseAttachedModifierGroupResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttachedModifierGroupResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        AttachedModifierGroupResponse: {
            /** Format: int32 */
            sortOrder?: number;
            group?: components["schemas"]["ModifierGroupResponse"];
        };
        GuestSessionRequest: {
            qrToken: string;
        };
        ApiResponseGuestSessionResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GuestSessionResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        GuestSessionResponse: {
            accessToken?: string;
            /** Format: int64 */
            expiresInMs?: number;
            /** Format: uuid */
            sessionId?: string;
            tableNumber?: string;
        };
        ApiResponseGuestOrdersResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GuestOrdersResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        GuestOrdersResponse: {
            /** Format: uuid */
            sessionId?: string;
            rounds?: components["schemas"]["OrderRoundResponse"][];
            currencyCode?: string;
            runningGrandTotal?: number;
            runningGrandTotalKhr?: number;
        };
        ExchangeRateCreateRequest: {
            fromCurrencyCode: string;
            toCurrencyCode: string;
            rate: number;
            /** Format: date */
            effectiveDate: string;
        };
        CategoryCreateRequest: {
            nameEn: string;
            nameKm: string;
            description?: string;
            /** Format: int32 */
            sortOrder: number;
            active?: boolean;
        };
        UserCreateRequest: {
            username: string;
            /** Format: email */
            email: string;
            password: string;
            roles: ("ADMIN" | "CASHIER")[];
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        ApiResponseLoginResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["LoginResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        LoginResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInMs?: number;
        };
        ApiResponseListUserResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageResponseTableResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseTableResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageResponseTableResponse: {
            content?: components["schemas"]["TableResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ApiResponseListTableOverviewResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TableOverviewResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        TableOverviewResponse: {
            /** Format: uuid */
            tableId?: string;
            tableNumber?: string;
            /** @enum {string} */
            state?: "IDLE" | "ORDERED" | "SERVED";
            /** Format: uuid */
            sessionId?: string;
            /** Format: int32 */
            openRoundCount?: number;
            runningTotal?: number;
        };
        ApiResponseListCashierRoundResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CashierRoundResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseBillResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BillResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponsePageResponseModifierGroupResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseModifierGroupResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageResponseModifierGroupResponse: {
            content?: components["schemas"]["ModifierGroupResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ApiResponsePageResponseMenuItemResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseMenuItemResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageResponseMenuItemResponse: {
            content?: components["schemas"]["MenuItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        ApiResponseListAttachedModifierGroupResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AttachedModifierGroupResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseGuestMenuItemDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GuestMenuItemDetailResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        GuestMenuItemDetailResponse: {
            item?: components["schemas"]["MenuItemResponse"];
            modifierGroups?: components["schemas"]["AttachedModifierGroupResponse"][];
        };
        ApiResponseListCategoryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CategoryResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListExchangeRateResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ExchangeRateResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListCurrencyResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CurrencyResponse"][];
            /** Format: date-time */
            timestamp?: string;
        };
        CurrencyResponse: {
            /** Format: uuid */
            id?: string;
            code?: string;
            name?: string;
            symbol?: string;
            defaultCurrency?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponsePageResponseCategoryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageResponseCategoryResponse"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageResponseCategoryResponse: {
            content?: components["schemas"]["CategoryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTableResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TableUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTableResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    markReady: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCashierRoundResponse"];
                };
            };
        };
    };
    voidLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                lineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCashierRoundResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCashierRoundResponse"];
                };
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseModifierGroupResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifierGroupUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseModifierGroupResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMenuItemResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuItemUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMenuItemResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lineId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartLineUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartResponse"];
                };
            };
        };
    };
    removeLine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lineId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRateUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExchangeRateResponse"];
                };
            };
        };
    };
    getById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryResponse"];
                };
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryResponse"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseTableResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TableCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTableResponse"];
                };
            };
        };
    };
    openSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStaffSessionResponse"];
                };
            };
        };
    };
    regenerateQrToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTableResponse"];
                };
            };
        };
    };
    getSessionRounds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCashierRoundResponse"];
                };
            };
        };
    };
    submitRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashierRoundRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCashierRoundResponse"];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReceiptResponse"];
                };
            };
        };
    };
    getAll_1: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseModifierGroupResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifierGroupCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseModifierGroupResponse"];
                };
            };
        };
    };
    getAll_2: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
                categoryId?: string;
                available?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseMenuItemResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuItemCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMenuItemResponse"];
                };
            };
        };
    };
    getForMenuItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuItemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAttachedModifierGroupResponse"];
                };
            };
        };
    };
    attach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuItemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachModifierGroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAttachedModifierGroupResponse"];
                };
            };
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMenuItemResponse"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGuestSessionResponse"];
                };
            };
        };
    };
    send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGuestOrdersResponse"];
                };
            };
        };
    };
    addLine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartLineAddRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartResponse"];
                };
            };
        };
    };
    getAll_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListExchangeRateResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeRateCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExchangeRateResponse"];
                };
            };
        };
    };
    getAll_4: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseCategoryResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCategoryResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResponse"];
                };
            };
        };
    };
    getAll_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListUserResponse"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTableOverviewResponse"];
                };
            };
        };
    };
    getBySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReceiptResponse"];
                };
            };
        };
    };
    getBill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBillResponse"];
                };
            };
        };
    };
    getQueue: {
        parameters: {
            query?: {
                status?: "SENT" | "READY" | "COMPLETED" | "CANCELLED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCashierRoundResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReceiptResponse"];
                };
            };
        };
    };
    pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGuestOrdersResponse"];
                };
            };
        };
    };
    getItems: {
        parameters: {
            query: {
                categoryId?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseMenuItemResponse"];
                };
            };
        };
    };
    getItemDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGuestMenuItemDetailResponse"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCategoryResponse"];
                };
            };
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartResponse"];
                };
            };
        };
    };
    clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCartResponse"];
                };
            };
        };
    };
    getAll_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCurrencyResponse"];
                };
            };
        };
    };
    detach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menuItemId: string;
                modifierGroupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
